version: "3"
services:
  ratelimiterapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TIME_INTERVAL: 1
      MAX_REQUESTS: 100
      INDIVIDUAL_TIME_SLOT: 5
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
    ports:
      - 8080:8080
  redis:
    image: redis:4.0.7
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis